kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: l01p02-go-app
  namespace: florian-ns
spec:
  output:
    to:
      kind: DockerImage
      name: "quay.io/neutron-it/l01p02-go_app:latest"
    pushSecret:
      name: florian-even-pull-secret
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: "registry.access.redhat.com/ubi8/go-toolset:latest"
  source:
    type: Git
    git:
      uri: "git@github.com:neutron-IT-organization/formation-openshift.git"
    contextDir: /content/02_Interface_et_ligne_de_commande/sources/l01p02
    sourceSecret:
      name: github-deploy-key
