site_name: My Docs
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
plugins:
- search
repo_url: https://github.com/neutron-IT-organization/formation-openshift
repo_name: neutron-IT-organization/formation-openshift
docs_dir: content
markdown_extensions:
- toc:
    toc_depth: "2-3"
nav:
- 'Introduction':
  - openshift/index.md
  - openshift/01_rhel-installation.md
  - openshift/02_microshift-installation.md
  - openshift/03_microshift-connection.md
  - openshift/04_add-console.md
  - openshift/05_configure-storage.md
- 'Additional Setup':
  - add-setup/index.md
  - add-setup/01_openvpn.md
  - add-setup/02_keycloak.md
  - add-setup/03_install_wordpress.md
  - add-setup/04_cyberark.md
  - add-setup/05_kubeburner.md
