site_name: My Docs
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
plugins:
- search
repo_url: https://github.com/neutron-IT-organization/formation-openshift
repo_name: neutron-IT-organization/formation-openshift
docs_dir: content
markdown_extensions:
- toc:
    toc_depth: "2-3"
nav:
- 'Introduction':
  - 00_Introduction/00_Objectif_du_cours.md
  - 00_Introduction/01_Organisation_de_la_classe.md
- 'Partie 1':
  - 'Présentation de Kubernetes et Openshift' :
    - 01_Présentation_de_Kubernetes_et_Openshift/00_Composant_de_Openshift.md
    - 01_Présentation_de_Kubernetes_et_Openshift/01_Quiz_Composant_de_Openshift.md
    - 01_Présentation_de_Kubernetes_et_Openshift/02_Exploration_de_la_console.md
    - 01_Présentation_de_Kubernetes_et_Openshift/03_Exercice_guidé_Exploration_de_la_console.md
  - 02_Interface_et_ligne_de_commande
- 'Partie 2':
  - 03_Executez_des_applications_conteneurisé
  - 04_Déployer_des_applications_en_réseau
  - 05_Gestion_du_stockage
- 'Partie 3':
  - 06_Configuration_de_la_fiabilité_des_applications
  - 07_Gestion_des_mises_à_jour_des_applications