site_name: Formation Kubernets/Openshift
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
  logo: assets/logo.png
plugins:
  - search
repo_url: https://github.com/neutron-IT-organization/formation-openshift
repo_name: neutron-IT-organization/formation-openshift
docs_dir: content
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - toc:
      toc_depth: "2-3"
nav:
  - "Introduction":
      - 00_Introduction/00_Objectif_du_cours.md
      - 00_Introduction/01_Organisation_de_la_formation.md
  - "Présentation de Kubernetes et Openshift":
      - 01_Présentation_de_Kubernetes_et_Openshift/00_Presentation_d_Openshift.md
      - 01_Présentation_de_Kubernetes_et_Openshift/01_Quiz_Presentation_d_Openshift.md
      - 01_Présentation_de_Kubernetes_et_Openshift/02_Exploration_de_la_console.md
      - 01_Présentation_de_Kubernetes_et_Openshift/03_Exercice_guidé_Exploration_de_la_console.md
      - 01_Présentation_de_Kubernetes_et_Openshift/04_Architecture_Openshift_et_Kubernetes.md
      - 01_Présentation_de_Kubernetes_et_Openshift/05_Quiz_Architecture_Openshift_et_Kubernetes.md
      - 01_Présentation_de_Kubernetes_et_Openshift/06_Résumé.md
  - "Interface et ligne de commande":
      - 02_Interface_et_ligne_de_commande/00_Intéragir_avec_la_ligne_de_commande.md
      - 02_Interface_et_ligne_de_commande/01_Exerice_guidé_Intéragir_avec_la_ligne_de_commande.md
      - 02_Interface_et_ligne_de_commande/02_Examen_des_ressources_Kubernetes.md
      - 02_Interface_et_ligne_de_commande/03_Exercice_guidé_Examen_des_ressources_Kubernetes.md
      - 02_Interface_et_ligne_de_commande/04_Résumé.md
  - "Exécuter des applications conteneurisées":
      - 03_Executez_des_applications_conteneurisé/00_Les_Workloads_dans_Openshift.md
      - 03_Executez_des_applications_conteneurisé/01_Quiz_Les_Workloads_dans_Openshift.md
      - 03_Executez_des_applications_conteneurisé/02_Les_deployment_et_les_daemonset.md
      - 03_Executez_des_applications_conteneurisé/03_Exercice_guidé_Les_deployment_et_les_daemonset.md
      - 03_Executez_des_applications_conteneurisé/04_Les_statefulset.md
      - 03_Executez_des_applications_conteneurisé/05_Exercice_guidé_Les_statefulset.md
      - 03_Executez_des_applications_conteneurisé/06_Résumé.md
  - "Les réseaux dans Openshift":
      - 04_Les_réseaux_dans_openshift/00_Les_sdn_dans_openshift.md
      - 04_Les_réseaux_dans_openshift/01_Quiz_Les_sdn_dans_openshift.md
      - 04_Les_réseaux_dans_openshift/02_Les_réseaux_de_pods_et_de_services.md
      - 04_Les_réseaux_dans_openshift/03_Exercice_guidé_Les_réseaux_de_pods_et_de_services.md
      - 04_Les_réseaux_dans_openshift/04_Résumé.md
  - "Gestion du stockage":
      - 05_Gestion_du_stockage/00_Les_configmap_et_les_secrets_dans_openshift.md
      - 05_Gestion_du_stockage/01_Exercice_guidé_Les_configmap_et_les_secrets_dans_openshifts.md
      - 05_Gestion_du_stockage/02_Approvisionnement_des_volumes_de_donnés_persistantes.md
      - 05_Gestion_du_stockage/03_Selection_d_une_classe_de_stockage.md
      - 05_Gestion_du_stockage/04_Exercice_guidé_pv_pvc_storage_class.md
      - 05_Gestion_du_stockage/05_Résumé.md
  - "Configuration de la fiabilité des applications":
      - 06_Configuration_de_la_fiabilité_des_applications/00_Gestion_de_la_haute_disponibilité_dans_Kubernetes.md
      - 06_Configuration_de_la_fiabilité_des_applications/01_Exercice_guidé_Gestion_de_la_haute_disponibilité_dans_Kubernetes.md
      - 06_Configuration_de_la_fiabilité_des_applications/02_Utilisation_des_probes_dans_Kubernetes.md
      - 06_Configuration_de_la_fiabilité_des_applications/03_Exercice_guidé_Utilisation_des_probes_dans_Kubernetes.md
      - 06_Configuration_de_la_fiabilité_des_applications/04_Réservation_de_capacité_de_calcul_pour_les_applications.md
      - 06_Configuration_de_la_fiabilité_des_applications/05_Exercice_guidé_Réservation_de_capacité_de_calcul_pour_les_applications.md
      - 06_Configuration_de_la_fiabilité_des_applications/06_Limitation_de_la_capacité_de_calcul_pour_les_applications.md
      - 06_Configuration_de_la_fiabilité_des_applications/07_Exercice_guidé_Limitation_de_la_capacité_de_calcul_pour_les_applications.md
      - 06_Configuration_de_la_fiabilité_des_applications/08_Mise_a_l'echelle_automatique_des_applications.md
      - 06_Configuration_de_la_fiabilité_des_applications/09_Exercice_guidé_Mise_a_l'echelle_automatique_des_applications.md
      - 06_Configuration_de_la_fiabilité_des_applications/10_Résumé.md
  - "Gestion des mises à jour des applications":
      - 07_Gestion_des_mises_à_jour_des_applications/00_Identité_et_balise_d_image_de_conteneur.md
      - 07_Gestion_des_mises_à_jour_des_applications/01_Exercice_guidé_Identité_et_balise_d_image_de_conteneur.md
      - 07_Gestion_des_mises_à_jour_des_applications/02_Mise_a_jour_des_parametres_et_de_l'image_de_l_application.md
      - 07_Gestion_des_mises_à_jour_des_applications/03_Exercice_guidé_Mise_a_jour_des_parametres_et_de_l'image_de_l_application.md
      - 07_Gestion_des_mises_à_jour_des_applications/04_Deploiement_automatique_avec_les_images_stream_openshift.md
      - 07_Gestion_des_mises_à_jour_des_applications/05_Exercice_guidé_Deploiement_automatique_avec_les_images_stream_openshift.md
      - 07_Gestion_des_mises_à_jour_des_applications/06_Mise_a_jour_automatique_avec_les_trigger_Kubernetes.md
      - 07_Gestion_des_mises_à_jour_des_applications/07_Exercice_guidé_Mise_a_jour_automatique_avec_les_trigger_Kubernetes.md
