site_name: My Docs
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
plugins:
- search
repo_url: https://github.com/neutron-IT-organization/formation-openshift
repo_name: neutron-IT-organization/formation-openshift
docs_dir: content
markdown_extensions:
- toc:
    toc_depth: "2-3"
nav:
- 'Introduction':
  - openshift/index.md
- 'Partie 1':
  - 00_Introduction
  - 01_Présentation_de_Kubernetes_et Openshift
  - 02_Interface_et_ligne_de_commande
- 'Partie 2':
  - 03_Executez_des_applications_conteneurisé
  - 04_Déployer_des_applications_en_réseau
  - 05_Gestion_du_stockage
- 'Partie 3':
  - 06_Configuration_de_la_fiabilité_des_applications
  - 07_Gestion_des_mises_à_jour_des_applications